### ISSUE TITLE
How can I change the screen resolution?

### ISSUE THREAD

**Issue by Yu65535** [apop2/GopRotate#1]
The screen resolution is currently 600x800, and when applying the rotation feature, some of the screen is not displayed (black screen). I would like to know how to simultaneously change my screen resolution to 800x600. Thank you.

**Comment by apop2** [comment]
That is outside of the scope of Gop Rotate. Gop Rotate, in the GopRotateBlt function, will take the BLT buffer and transpose it to the desired rotation. It still limits the output based on the original screen dimensions reported from the Gop screen resolution.

I think what you are trying to support is, 600x800, is a change to the GraphicsConsoleDxe which will map a Gop Mode into something that will fit the full range of 600x800.  

https://github.com/tianocore/edk2/blob/master/MdeModulePkg/Universal/Console/GraphicsConsoleDxe/GraphicsConsole.c#L451

Today, the logic contained is attempting to map an EFI_NARROW_GLYPH into the resolutions (8 bits wide into horizontal resolution, 19 bits high into vertical resolution),


You can try to change the logic into the function to map into the 8 bits into the vertical resolution and the 19 bits into the horizontal resolution instead.
